# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "68b327ae97a3b05646394669c6002db9"
name = "NovaPoshtaRemake"
application_url = "http://localhost:3000/"
embedded = true
handle = "novaposhtaremake"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  # [[webhooks.subscriptions]]
  # topics = [ "app/uninstalled" ]
  # uri = "/webhooks/app/uninstalled"

  # [[webhooks.subscriptions]]
  # topics = [ "app/scopes_update" ]
  # uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [ "http://localhost:3000/api/auth" ]

[pos]
embedded = false
